[package]
edition = "2021"
name = "kvstore"
version = "0.1.0"

[[bin]]
name = "kvs"
path = "src/server.rs"

[[bin]]
name = "kvc"
path = "src/client.rs"

[[bin]]
name = "gen_cert"
path = "tools/gen_cert.rs"

[[bin]]
name = "gen_config"
path = "tools/gen_config.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1" 
bytes = "1" 
certify = "0.3" 
dashmap = "4" # 并发 HashMap
flate2 = "1" # gzip 压缩
futures = "0.3.19" # 提供 Stream trait
http = "0.2" 
opentelemetry-jaeger = "0.15" 
prost = "0.8" 
rustls-native-certs = "0.5" 
serde = {version = "1", features = ["derive"]}# 序列化/反序列化 
sled = "0.34" 

thiserror = "1" 
tokio = {version = "1", features = ["full"]}# 异步网络库 
tokio-rustls = "0.22" 
tokio-stream = {version = "0.1", features = ["sync"]}# 处理 stream 
tokio-util = {version = "0.6", features = ["compat"]}# tokio 和 futures 的兼容性库 
toml = "0.5" 
tracing = "0.1" # 日志处理
tracing-appender = "0.1" # 文件日志
tracing-opentelemetry = "0.15" # opentelemetry 支持
tracing-subscriber = {version = "0.2", features = ["json", "chrono"]}# 日志处理 
yamux = "0.9" 

[dev-dependencies]
criterion = {version = "0.3", features = ["async_futures", "async_tokio", "html_reports"]}# benchmark 
rand = "0.8" # 随机数处理
tempfile = "3" # 处理临时目录和临时文件

[build-dependencies]
prost-build = "0.8"
